---
abstract: ' Automatically makes references weaken'
author:
  - 'Goro Fuji <gfuji(at)cpan.org>.'
build_requires:
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.44
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WeakRef-Auto
no_index:
  directory:
    - inc
    - t
requires:
  Exporter: 5.57
  XSLoader: 0.06
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
